rm -f lib/GAL/t/data/dmel-4-r5.24.partial.sqlite
rm -f lib/GAL/t/data/test_storage.sqlite
rm -f t/data/dmel-4-r5.46.genes.sqlite
rm -f t/data/10Gen_Korean_SNV_chr22.sqlite
rm -f t/data/refseq_chr22.trim.sqlite
rm -f t/data/directory.index
rm -f t/data/fasta_hg18/chr22_hg18.fasta.index
rm -f t/data/test_storage.sqlite
rm -f t/data/dmel-4-r5.24.partial.sqlite
rm -f t/data/dmel-4-r5.46.genes.sqlite
rm -f t/data/test_storage.sqlite
rm -f t/data/dmel-4-r5.24.partial.sqlite
rm -f t/data/dmel-4-r5.46.genes.sqlite
rm -f t/data/directory.index
rm -f t/data/fasta_hg18/chr22_hg18.fasta.index
rm -f bin/t/vaast_run_std*