rm -f b/GAL/t/data/dmel-4-r5.24.partial.sqlite
rm -f b/GAL/t/data/test_storage.sqlite
rm -f data/10Gen_Chinese_SNV_chr22.sqlite
rm -f data/10Gen_Chinese_SNV_partial.sqlite
rm -f data/10Gen_Korean_SNV_chr22.sqlite
rm -f data/directory.index
rm -f data/dmel-4-chromosome-r5.46.fasta.index
rm -f data/dmel-4-r5.24.partial.sqlite
rm -f data/dmel-4-r5.46.genes.partial.sqlite
rm -f data/dmel-4-r5.46.genes.sqlite
rm -f data/dmel-4-r5.46.infer_UTR.gff
rm -f data/dmel-4-r5.46.no_UTR.sqlite
rm -f data/dmel-4-r5.46.sqlite
rm -f data/fasta_hg18/chr22_hg18.fasta.index
rm -f data/hg18_chr22.fa.index
rm -f data/hg19_chr22.fa.index
rm -f data/refseq_chr22.trim.sqlite
rm -f data/test_storage.sqlite
rm -f data/urt_new.txt
rm -f data/urt_original.txt
rm -f in/examples/nytprof
rm -f n/examples/nytprof.out
rm -f n/t/.sqlite
rm -f n/t/37d6f729.sqlite
rm -f n/t/gal_run_stderr_*
rm -f n/t/gal_run_stdout_*
rm -f n/t/vaast_run_std*
rm -f t/data/10Gen_Chinese_SNV_partial.sqlite
rm -f t/data/dmel-4-chromosome-r5.46.fasta.index
rm -f t/data/dmel-4-r5.24.partial.sqlite
rm -f t/data/dmel-4-r5.46.genes.partial.sqlite
rm -f t/data/dmel-4-r5.46.genes.sqlite
rm -f t/data/dmel-4-r5.46.no_UTR.sqlite
rm -f t/data/fasta_hg18/chr22_hg18.fasta.index
rm -f t/data/hg18_chr22.fa.index
rm -f t/data/hg19_chr22.fa.index
rm -f t/data/refseq_chr22.trim.sqlite
rm -f t/data/test_storage.sqlite
rm -f bin/t/gal_run_stdout*
rm -f bin/t/gal_run_stderr*
