rm -f t/data/dmel-4-r5.24.partial.sqlite
rm -f t/data/test_storage.sqlite
rm -f t/data/10Gen_Chinese_SNV_chr22.sqlite
rm -f t/data/10Gen_Chinese_SNV_partial.sqlite
rm -f t/data/10Gen_Korean_SNV_chr22.sqlite
rm -f t/data/directory.index
rm -f t/data/dmel-4-chromosome-r5.46.fasta.index
rm -f t/data/dmel-4-r5.24.partial.sqlite
rm -f t/data/dmel-4-r5.46.genes.partial.sqlite
rm -f t/data/dmel-4-r5.46.genes.sqlite
rm -f t/data/dmel-4-r5.46.infer_UTR.gff
rm -f t/data/dmel-4-r5.46.no_UTR.sqlite
rm -f t/data/dmel-4-r5.46.sqlite
rm -f t/data/fasta_hg18/chr22_hg18.fasta.index
rm -f t/data/hg18_chr22.fa.index
rm -f t/data/hg19_chr22.fa.index
rm -f t/data/refseq_chr22.trim.sqlite
rm -f t/data/test_storage.sqlite
rm -f t/data/urt_new.txt
rm -f t/data/urt_original.txt
rm -f t/data/10Gen_Chinese_SNV_partial.sqlite
rm -f t/data/dmel-4-chromosome-r5.46.fasta.index
rm -f t/data/dmel-4-r5.24.partial.sqlite
rm -f t/data/dmel-4-r5.46.genes.partial.sqlite
rm -f t/data/dmel-4-r5.46.genes.sqlite
rm -f t/data/dmel-4-r5.46.no_UTR.sqlite
rm -f t/data/fasta_hg18/chr22_hg18.fasta.index
rm -f t/data/hg18_chr22.fa.index
rm -f t/data/hg19_chr22.fa.index
rm -f t/data/refseq_chr22.trim.sqlite
rm -f t/data/test_storage.sqlite
rm -f t/data/Homo_sapiens.GRCh37.73.chr22.short.sqlite
rm -f bin/t/gal_run_stdout*
rm -f bin/t/gal_run_stderr*
rm -f t/data/fasta_hg18/directory.index