#!/usr/bin/perl

use FindBin;
use TAP::Harness;

my %args = (verbosity => -1,
	    lib       => ["$FindBin::Bin/../lib"],
	    timer     => 1,
	    show_count => 1,
	    merge        => 1,
	    );

my $harness = TAP::Harness->new( \%args );

my @tests = ('../lib/GAL/t/001_annotation.t',
	     '../lib/GAL/t/001_base.t',
	     '../lib/GAL/t/001_index.t',
	     '../lib/GAL/t/001_pod_coverage.t',
	     '../lib/GAL/t/001_test_template.t',
	     '../lib/GAL/t/100_feature.t',
	     '../lib/GAL/t/100_feature_sequence_alteration.t',
	     '../lib/GAL/t/100_feature_sequence_feature.t',
	     '../lib/GAL/t/200_parser.t',
	     '../lib/GAL/t/200_parser_basic_snp.t',
	     '../lib/GAL/t/200_parser_complete_genomics.t',
	     '../lib/GAL/t/200_parser_complete_genomics_new.t',
	     '../lib/GAL/t/200_parser_cosmic.t',
	     '../lib/GAL/t/200_parser_dbsnp_flat.t',
	     '../lib/GAL/t/200_parser_gff3.t',
	     '../lib/GAL/t/200_parser_hapmap_genotypes.t',
	     '../lib/GAL/t/200_parser_korean_indel.t',
	     '../lib/GAL/t/200_parser_korean_snp.t',
	     '../lib/GAL/t/200_parser_maq_cns2snp.t',
	     '../lib/GAL/t/200_parser_na18507_sanger_indel.t',
	     '../lib/GAL/t/200_parser_quake.t',
	     '../lib/GAL/t/200_parser_samtools_pileup.t',
	     '../lib/GAL/t/200_parser_smith_ant_snps.t',
	     '../lib/GAL/t/200_parser_soap_indel.t',
	     '../lib/GAL/t/200_parser_soap_snp.t',
	     '../lib/GAL/t/200_parser_solid.t',
	     '../lib/GAL/t/200_parser_template.t',
	     '../lib/GAL/t/200_parser_template_sequence_alteration.t',
	     '../lib/GAL/t/200_parser_trait_o_matic.t',
	     '../lib/GAL/t/200_parser_vcfv4_0.t',
	     '../lib/GAL/t/200_parser_venter_indel.t',
	     '../lib/GAL/t/200_parser_venter_snp.t',
	     '../lib/GAL/t/200_parser_watson_cshl.t',
	     '../lib/GAL/t/300_reader.t',
	     '../lib/GAL/t/300_reader_delimitedline.t',
	     '../lib/GAL/t/300_reader_recordparser.t',
	     '../lib/GAL/t/300_reader_template.t',
	     '../lib/GAL/t/400_storage.t',
	     '../lib/GAL/t/400_storage_mysql.t',
	     '../lib/GAL/t/400_storage_sqlite.t',
	     '../lib/GAL/t/500_schema.t',
	     '../lib/GAL/t/500_schema_result_attribute.t',
	     '../lib/GAL/t/500_schema_result_feature.t',
	     '../lib/GAL/t/500_schema_result_feature_cds.t',
	     '../lib/GAL/t/500_schema_result_feature_exon.t',
	     '../lib/GAL/t/500_schema_result_feature_five_prime_utr.t',
	     '../lib/GAL/t/500_schema_result_feature_gene.t',
	     '../lib/GAL/t/500_schema_result_feature_intron.t',
	     '../lib/GAL/t/500_schema_result_feature_mrna.t',
	     '../lib/GAL/t/500_schema_result_feature_mrna_BIG.t',
	     '../lib/GAL/t/500_schema_result_feature_protein.t',
	     '../lib/GAL/t/500_schema_result_feature_sequence_alteration.t',
	     '../lib/GAL/t/500_schema_result_feature_sequence_feature.t',
	     '../lib/GAL/t/500_schema_result_feature_template.t',
	     '../lib/GAL/t/500_schema_result_feature_three_prime_utr.t',
	     '../lib/GAL/t/500_schema_result_feature_transcript.t',
	     '../lib/GAL/t/500_schema_result_feature_transcript_BIG.t',
	     '../lib/GAL/t/500_schema_result_realtionship.t',
	     '../lib/GAL/t/600_list.t',
	     '../lib/GAL/t/600_list_categorical.t',
	     '../lib/GAL/t/600_list_numeric.t',
	     '../lib/GAL/t/600_list_span.t',
	     #'../bin/t/feature2gff_test.sh',
	     #'../bin/t/feature_overlaps.sh',
	     #'../bin/t/gff_tool.sh',
	     #'../bin/t/gvf_tool.t.sh',
	     #'../lib/GAL/t/devel_scripts/annotation_basic.pl',
	     #'../lib/GAL/t/devel_scripts/annotation_existing.pl',
	     #'../lib/GAL/t/devel_scripts/annotation_load_file.pl',
	     #'../lib/GAL/t/devel_scripts/parser_1000_genomes_genotypes.pl',
	     #'../lib/GAL/t/devel_scripts/parser_complete_genomics.pl',
	     #'../lib/GAL/t/devel_scripts/parser_dbsnp_flat.pl',
	     #'../lib/GAL/t/devel_scripts/parser_korean_indel.pl',
	     #'../lib/GAL/t/devel_scripts/parser_na18507_indel.pl',
	     #'../lib/GAL/t/devel_scripts/parser_quake.pl',
	     #'../lib/GAL/t/devel_scripts/parser_samtools_pileup.pl',
	     #'../lib/GAL/t/devel_scripts/parser_smith_ant_snps.pl',
	     #'../lib/GAL/t/devel_scripts/parser_soap_indel.pl',
	     #'../lib/GAL/t/devel_scripts/parser_soap_snp.pl',
	     #'../lib/GAL/t/devel_scripts/parser_trait_o_matic.pl',
	     #'../lib/GAL/t/devel_scripts/parser_venter_indel.pl',
	     #'../lib/GAL/t/devel_scripts/schema_cursor.pl',
	     #'../lib/GAL/t/devel_scripts/schema_dbi.pl',
	     #'../lib/GAL/t/devel_scripts/schema_hash.pl',
	     #'../lib/GAL/t/devel_scripts/schema_mysql.pl',
	     #'../lib/GAL/t/devel_scripts/schema_object.pl',
	     #'../lib/GAL/t/devel_scripts/storage_mysql.pl',
	    );

$harness->runtests(@tests);
